from __future__ import annotations

import hashlib
import importlib.util
import json
import subprocess
import sys
from argparse import Namespace
from pathlib import Path
from unittest.mock import patch

from PIL import Image

from infra.runtime import ExecutionPolicy


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_PATH = REPO_ROOT / "scripts" / "qualify_real_models.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("qualify_real_models", SCRIPT_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _manifest(image_sha: str, artifact_sha: str) -> dict[str, object]:
    return {
        "manifest_version": 1,
        "fixture_id": "licensed-real-face-fixture-v1",
        "fixture_license": "Test-only generated placeholder; real qualification must supply approved face media.",
        "fixture_source": "Generated by this test; not valid real-model qualification media.",
        "required_coverage": {
            "detectors": ["fixture-detector"],
            "embedders": ["fixture-embedder"],
            "clustering_backends": ["cosine-kmeans"],
        },
        "images": [
            {
                "path": "face.png",
                "sha256": image_sha,
                "expected_min_faces": {"fixture-detector": 1},
            }
        ],
        "model_cases": [
            {
                "case_id": "cpu-fixture",
                "mode": "human",
                "detector_id": "fixture-detector",
                "embedder_id": "fixture-embedder",
                "revision": "fixture-revision",
                "embedding_dimension": 512,
                "clustering_backends": ["cosine-kmeans"],
                "artifacts": [
                    {
                        "path": "model.onnx",
                        "sha256": artifact_sha,
                        "source": "Generated by this test.",
                        "license": "Test-only generated bytes.",
                    }
                ],
            }
        ],
    }


def test_manifest_requires_license_pins_and_safe_paths(tmp_path):
    qualify = _load_module()
    payload = _manifest("a" * 64, "b" * 64)
    payload["fixture_license"] = ""
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text(json.dumps(payload), encoding="utf-8")

    try:
        qualify._load_manifest(manifest_path)
    except ValueError as exc:
        assert "fixture_license" in str(exc)
    else:
        raise AssertionError("an unlicensed fixture manifest must be rejected")

    try:
        qualify._safe_relative(tmp_path, "../outside", label="fixture path")
    except ValueError as exc:
        assert "relative path" in str(exc)
    else:
        raise AssertionError("a manifest path escape must be rejected")


def test_manifest_rejects_incomplete_advertised_coverage():
    qualify = _load_module()
    payload = _manifest("a" * 64, "b" * 64)
    payload["required_coverage"]["detectors"].append("uncovered-detector")

    assert qualify._validate_case_coverage(payload) == [
        "required_coverage.detectors is missing cases for: uncovered-detector"
    ]


def test_manifest_rejects_non_hex_sha256(tmp_path):
    qualify = _load_module()
    fixture_root = tmp_path / "fixture"
    model_root = tmp_path / "models"
    fixture_root.mkdir()
    model_root.mkdir()
    payload = _manifest("z" * 64, "y" * 64)

    images, missing, failures = qualify._verify_inputs(
        payload,
        fixture_root=fixture_root,
        model_root=model_root,
    )

    assert images == []
    assert missing == []
    assert failures == [
        "images[0].sha256 must be a complete SHA-256",
        "model case cpu-fixture artifact SHA-256 is incomplete",
    ]


def test_missing_pinned_model_is_not_run_and_never_substituted(tmp_path):
    fixture_root = tmp_path / "fixture"
    model_root = tmp_path / "models"
    fixture_root.mkdir()
    model_root.mkdir()
    image_path = fixture_root / "face.png"
    Image.new("RGB", (64, 64), (20, 30, 40)).save(image_path)
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text(
        json.dumps(_manifest(_sha256(image_path), hashlib.sha256(b"missing-model").hexdigest())),
        encoding="utf-8",
    )
    report_path = tmp_path / "report.json"

    completed = subprocess.run(
        [
            sys.executable,
            "-B",
            str(SCRIPT_PATH),
            "--manifest",
            str(manifest_path),
            "--fixture-root",
            str(fixture_root),
            "--model-root",
            str(model_root),
            "--execution-mode",
            "cpu",
            "--report",
            str(report_path),
        ],
        cwd=REPO_ROOT,
        check=False,
        capture_output=True,
        text=True,
        timeout=30,
    )

    assert completed.returncode == 3, completed.stderr
    report = json.loads(report_path.read_text(encoding="utf-8"))
    assert report["status"] == "NOT_RUN"
    assert report["cases"] == []
    assert "model artifact missing" in report["not_run_reasons"][0]
    assert json.loads(completed.stdout) == report


def test_checksum_mismatch_is_failure_not_not_run(tmp_path):
    qualify = _load_module()
    fixture_root = tmp_path / "fixture"
    model_root = tmp_path / "models"
    fixture_root.mkdir()
    model_root.mkdir()
    image_path = fixture_root / "face.png"
    model_path = model_root / "model.onnx"
    Image.new("RGB", (64, 64)).save(image_path)
    model_path.write_bytes(b"actual")
    manifest = _manifest(_sha256(image_path), hashlib.sha256(b"expected").hexdigest())

    images, missing, failures = qualify._verify_inputs(
        manifest,
        fixture_root=fixture_root,
        model_root=model_root,
    )

    assert images
    assert missing == []
    assert failures == [f"model artifact checksum mismatch: {model_path}"]


def test_unavailable_explicit_cuda_is_not_run_before_inference(tmp_path):
    qualify = _load_module()
    fixture_root = tmp_path / "fixture"
    model_root = tmp_path / "models"
    fixture_root.mkdir()
    model_root.mkdir()
    image_path = fixture_root / "face.png"
    model_path = model_root / "model.onnx"
    Image.new("RGB", (64, 64)).save(image_path)
    model_path.write_bytes(b"pinned-but-not-loaded")
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text(
        json.dumps(_manifest(_sha256(image_path), _sha256(model_path))),
        encoding="utf-8",
    )

    class _UnavailableCudaRuntime:
        def select_policy(self, _mode):
            return ExecutionPolicy(
                preferred_mode="cuda",
                effective_mode="cpu",
                error="CUDA was explicitly requested but is unavailable.",
            )

    args = Namespace(
        manifest=manifest_path,
        fixture_root=fixture_root,
        model_root=model_root,
        execution_mode="cuda",
    )
    with patch("infra.runtime.RuntimeCapabilityService", _UnavailableCudaRuntime):
        report, exit_code = qualify.qualify(args)

    assert exit_code == qualify.EXIT_NOT_RUN
    assert report["status"] == "NOT_RUN"
    assert report["cases"] == []
    assert report["not_run_reasons"] == ["CUDA was explicitly requested but is unavailable."]
